### ISSUE TITLE
Possible expanding to Vue script tag

### ISSUE THREAD

**Issue by AEsmerio** [gyuha/quick-console-log#1]
I've tested your plugin and it's one of the fastest and most accurately console.log tool.

In there any chance to make it work with Vue files?

Apparently the extension works fine with Vue structure file format. If I replace the extension .vue to .js, it simply works.

**Comment by cycle4passion** [comment]
Same here, although I am mostly using Svelte.

**Comment by gyuha** [comment]
Thanks for issue..
sorry to late..
I will fix it and update...
