### ISSUE TITLE
QCL Enhancement - Empty Console Log

### ISSUE THREAD

**Issue by cycle4passion** [gyuha/quick-console-log#2]
Assume no text selection and cursor not overlying word

quick console log would insert a blank console log like:

`console.log("📢 [index.js:10]: ", "");`

Now how to implement this? This would seemingly fit nicely with "Log Current". I would also suggest that it fits for "Log Down" and "Log Up" as well although without end cursor repositioning.  By applying to all (Up, down, current) this functionality would benefit everyone as I expect that most users gravitate to a single option (I suspect "Log Down")

**Comment by gyuha** [comment]
Thanks for issue..
sorry to late..
I will fix it and update...
