### ISSUE TITLE
QCL Setting option to include variable labels

### ISSUE THREAD

**Issue by cycle4passion** [gyuha/quick-console-log#5]
If this option were enabled, and example would be

`myvar`

becomes

`console.log("📢[index.js:12]: myvar: ", myvar);`

or if you prefer

`console.log("📢[index.js:12]: ", "myvar", myvar);`

Thinking about it is should only work this way if the typeof were not a string, so

`"something happened here"`

should still be

`console.log("📢[index.js:12]: ", "something happened here");`

**Comment by gyuha** [comment]
Thanks for issue..
It's good idea...
I will fix it and update...
