### ISSUE TITLE
Separate `includeFileNameAndLineNum` into two options 

### ISSUE THREAD

**Issue by Kotsuha** [gyuha/quick-console-log#7]
I feel like `includeFileNameAndLineNum` can be separated into two options :)

Sometimes I insert a bunch of logs here and there when I'm debugging. The "line number" quickly becomes wrong.

```
289    private static FooDefinition GetFooData(string fooName)
290    {
291        TextAsset fooDataFile = Resources.Load<TextAsset>("FooData/" + fooName);
292        string rawFooData = fooDataFile.text;
293        Debug.Log("📢[FooManager.cs:293]: " + rawFooData);
294        //Destroy(fooDataFile);
295        var fooData = JsonConvert.DeserializeObject<FooDefinition>(rawFooData);
296        Debug.Log("📢[FooManager.cs:295]: " + fooData);
297        return fooData;
298    }
```

Insert `[FooManager.cs:295]` first and then insert `[FooManager.cs:293]`. The `[FooManager.cs:295]` line number becomes wrong. The file name is still helpful.

**Comment by gyuha** [comment]
Thank you for your feedback. I'll try to update it soon.

**Comment by gyuha** [comment]
Thanks for your pull request... release now...
